# azure-pipelines.yml
trigger:
  branches:
    include:
      - main  # Change to your main branch

pool:
  vmImage: 'ubuntu-latest'  # Use the latest Ubuntu image

variables:
  mavenVersion: '3.6.3'
  javaVersion: '11'  # Specify the Java version

stages:
- stage: Build
  displayName: 'Build and Test'
  jobs:
  - job: Build
    displayName: 'Build Job'
    steps:
    - checkout: self  # Ensure the code is checked out
    - task: Maven@3
      inputs:
        mavenPomFile: 'javaSpringBoot-master/pom.xml'  # Adjust this path if necessary
        goals: 'clean package'
        options: '-DskipTests=true'
        mavenVersionOption: 'Default'
        publishJUnitResults: true
        testResultsFiles: '**/target/surefire-reports/*.xml'
        codeCoverageToolOption: 'None'